# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ew8f_z3CUfdMHvxcl4Cg0HJoL_e4K3lH
"""

import os
import io
import uuid
import warnings
import uvicorn
from PIL import Image
from fastapi import FastAPI, Request, HTTPException
from fastapi.responses import Response
from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import MessageEvent, ImageMessage, TextSendMessage, ImageSendMessage
from google import genai
from google.genai import types

app = FastAPI()
image_store = {}

# 從 Zeabur 的環境變數讀取金鑰，不要寫死在程式碼裡
GEMINI_KEY = os.getenv("AIzaSyAVJ1e0v5ramDHm2MpQqBaYGGlB-EjQBjg")
LINE_SECRET = os.getenv("1444f2a0008343b59de050ac52037ef4")
LINE_TOKEN = os.getenv("vpoqYbSS4cDYLIXaMyBNUaFX+NnJIebG4MyXX660CwzVRjcfOw81BwtGQcc+XRFVwdkBa5NWOm6N0TJrLCEm4635bpQplR7PEFu3xEUNSVVz8uGucTjIpsQpgN5CoXERfXkQ9pen/odZK0yzH72emAdB04t89/1O/w1cDnyilFU=")

line_bot_api = LineBotApi(LINE_TOKEN)
handler = WebhookHandler(LINE_SECRET)
gemini_client = genai.Client(api_key=GEMINI_KEY)

@app.get("/")
def health_check():
    return {"status": "running"}

@app.get("/images/{image_id}")
def serve_image(image_id: str):
    if image_id in image_store:
        return Response(content=image_store[image_id], media_type="image/jpeg")
    raise HTTPException(status_code=404)

@app.post("/callback")
async def callback(request: Request):
    signature = request.headers.get("X-Line-Signature")
    body = await request.body()
    try:
        handler.handle(body.decode(), signature)
    except InvalidSignatureError:
        raise HTTPException(status_code=400)
    return "OK"

@handler.add(MessageEvent, message=ImageMessage)
def handle_image(event):
    message_content = line_bot_api.get_message_content(event.message.id)
    input_image_bytes = io.BytesIO(message_content.content).read()

    line_bot_api.reply_message(event.reply_token, TextSendMessage(text="📸 收到圖片！AI 正在分析並標註..."))

    try:
        response = gemini_client.models.generate_content(
            model="gemini-3-flash-preview",
            contents=[
                types.Part.from_bytes(data=input_image_bytes, mime_type="image/jpeg"),
                "請找出圖中的重要物件，並執行程式碼來繪製紅框標註圖片。不要顯示 JSON。請用繁體中文給予簡短描述。"
            ],
            config=types.GenerateContentConfig(
                tools=[types.Tool(code_execution=types.ToolCodeExecution())],
                thinking_config=types.ThinkingConfig(thinking_budget=2048),
                max_output_tokens=2048
            )
        )

        text_result = ""
        annotated_image_bytes = None
        for part in response.candidates[0].content.parts:
            if part.text and "box_2d" not in part.text:
                text_result += part.text
            if part.as_image():
                annotated_image_bytes = part.as_image().image_bytes

        reply_messages = [TextSendMessage(text=text_result or "偵測完成")]
        if annotated_image_bytes:
            img_id = str(uuid.uuid4())
            image_store[img_id] = annotated_image_bytes
            # 自動獲取 Zeabur 給你的域名（需在環境變數設定或動取，此處建議手動在後台填一次）
            domain = os.getenv("ZEABUR_DOMAIN")
            image_url = f"https://{domain}/images/{img_id}"
            reply_messages.append(ImageSendMessage(original_content_url=image_url, preview_image_url=image_url))

        line_bot_api.push_message(event.source.user_id, reply_messages)
    except Exception as e:
        line_bot_api.push_message(event.source.user_id, TextSendMessage(text=f"AI 故障: {e}"))

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8080))
    uvicorn.run(app, host="0.0.0.0", port=port)